[package]
name = "wexc"
version = "0.1.2"
authors = ["lgmys <lgmys@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
